eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://user-microservices:yA5N1QVN7AzPiMZ8@gr-cluster.tucor.mongodb.net/test
